/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Julieth
 */
public class JFinicio extends javax.swing.JFrame {

    /**
     * Creates new form JFinicio
     */
    public JFinicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBgeneral = new javax.swing.JButton();
        jBventas = new javax.swing.JButton();
        JBproductos = new javax.swing.JButton();
        jBproveedores = new javax.swing.JButton();
        jfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBgeneral.setBackground(new java.awt.Color(156, 230, 255));
        jBgeneral.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBgeneral.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Desktop\\WorkSpace_SJ\\Proyecto\\InvdrogueriaMunich\\src\\main\\java\\img\\control-de-acceso.png")); // NOI18N
        jBgeneral.setText("  ACCESO GENERAL");
        jBgeneral.setBorder(null);
        jBgeneral.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBgeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgeneralActionPerformed(evt);
            }
        });
        jPanel1.add(jBgeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 50));

        jBventas.setBackground(new java.awt.Color(156, 230, 255));
        jBventas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBventas.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Desktop\\WorkSpace_SJ\\Proyecto\\InvdrogueriaMunich\\src\\main\\java\\img\\ventas.png")); // NOI18N
        jBventas.setText("   VENTAS");
        jBventas.setBorder(null);
        jBventas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBventasActionPerformed(evt);
            }
        });
        jPanel1.add(jBventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 50));

        JBproductos.setBackground(new java.awt.Color(156, 230, 255));
        JBproductos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBproductos.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Desktop\\WorkSpace_SJ\\Proyecto\\InvdrogueriaMunich\\src\\main\\java\\img\\productividad.png")); // NOI18N
        JBproductos.setText("   PRODUCTOS");
        JBproductos.setBorder(null);
        JBproductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JBproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBproductosActionPerformed(evt);
            }
        });
        jPanel1.add(JBproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 50));

        jBproveedores.setBackground(new java.awt.Color(156, 230, 255));
        jBproveedores.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBproveedores.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Desktop\\WorkSpace_SJ\\Proyecto\\InvdrogueriaMunich\\src\\main\\java\\img\\proveedor.png")); // NOI18N
        jBproveedores.setText("   PROVEEDORES");
        jBproveedores.setBorder(null);
        jBproveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBproveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(jBproveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 50));

        jfondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Desktop\\WorkSpace_SJ\\Proyecto\\InvdrogueriaMunich\\src\\main\\java\\img\\3925ce5fd9a7c47b6bc967fa6368c072.jpg")); // NOI18N
        jPanel1.add(jfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBventasActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jBventasActionPerformed

    private void JBproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBproductosActionPerformed

    private void jBproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBproveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBproveedoresActionPerformed

    private void jBgeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBgeneralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFinicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBproductos;
    private javax.swing.JButton jBgeneral;
    private javax.swing.JButton jBproveedores;
    private javax.swing.JButton jBventas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jfondo;
    // End of variables declaration//GEN-END:variables
}
