/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;

/**
 *
 * @author Julieth
 */
public class JFlogin1 extends javax.swing.JFrame {

    /**
     * Creates new form JFlogin1
     */
    public JFlogin1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextPass = new javax.swing.JPasswordField();
        jTxtUser1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPfondo = new javax.swing.JPanel();
        jBIngresar = new javax.swing.JButton();
        jBcerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtUser.setBorder(null);
        jTxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 440, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("INICIO DE SESIÓN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, 60));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 430, 10));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setText("USUARIO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 30));

        jTextPass.setBorder(null);
        getContentPane().add(jTextPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 440, 50));

        jTxtUser1.setBackground(new java.awt.Color(240, 240, 240));
        jTxtUser1.setBorder(null);
        jTxtUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUser1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 440, 50));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 430, 10));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setText("CONTRASEÑA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, 30));

        jPfondo.setBackground(new java.awt.Color(255, 255, 255));
        jPfondo.setForeground(new java.awt.Color(255, 255, 255));
        jPfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBIngresar.setBackground(new java.awt.Color(210, 230, 237));
        jBIngresar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBIngresar.setText("INGRESAR");
        jBIngresar.setBorder(null);
        jBIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresarActionPerformed(evt);
            }
        });
        jPfondo.add(jBIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 418, 120, 40));

        jBcerrar.setBackground(new java.awt.Color(255, 255, 255));
        jBcerrar.setForeground(new java.awt.Color(255, 255, 255));
        jBcerrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Julieth\\Downloads\\delete_96690.png")); // NOI18N
        jBcerrar.setBorder(null);
        jBcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBcerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBcerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBcerrarMouseExited(evt);
            }
        });
        jBcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcerrarActionPerformed(evt);
            }
        });
        jPfondo.add(jBcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Julieth\\Desktop\\WorkSpace_SJ\\MVC\\InvdrogueriaMunich\\src\\main\\java\\img\\medical-49_icon-icons.com_73913.png")); // NOI18N
        jPfondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 140, 180));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("DROGUERIA MUNICH");
        jPfondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 280, 60));

        Lfondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Julieth\\Desktop\\WorkSpace_SJ\\MVC\\InvdrogueriaMunich\\src\\main\\java\\img\\Medico.jpg")); // NOI18N
        jPfondo.add(Lfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 380, 550));

        getContentPane().add(jPfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUserActionPerformed

    private void jTxtUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUser1ActionPerformed

    private void jBIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBIngresarActionPerformed

    private void jBcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBcerrarActionPerformed

    private void jBcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBcerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBcerrarMouseClicked

    private void jBcerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBcerrarMouseEntered
        // TODO add your handling code here:
        jBcerrar.setBackground(Color.RED);
    }//GEN-LAST:event_jBcerrarMouseEntered

    private void jBcerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBcerrarMouseExited
       jBcerrar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jBcerrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFlogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFlogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFlogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFlogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFlogin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Lfondo;
    public javax.swing.JButton jBIngresar;
    public javax.swing.JButton jBcerrar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPfondo;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JPasswordField jTextPass;
    public javax.swing.JTextField jTxtUser;
    public javax.swing.JTextField jTxtUser1;
    // End of variables declaration//GEN-END:variables
}
